### PR TITLE
Diplay the field_name in case of validation error

### PR DESCRIPTION
**Pull request by ElielHaouzi**
Diplay the field_name in case of validation error, so the user know which field is unvalid.

### CODE REVIEW

**Comment by ElielHaouzi** [comment]
I didn't change the unit test. i will change them and then re-pull.

**Comment by jaimegildesagredo** [comment]
Hi @ElielHaouzi and thank you for your PR.

I would prefer the `validate` method to be as simple as possible just re-raising validation exceptions.

If you want to know the field a validation error comes from you can use the `validation_errors` iterable: https://github.com/jaimegildesagredo/booby/blob/master/booby/models.py#L185

Hope it helps.

**Comment by ElielHaouzi** [comment]
@jaimegildesagredo Great, You're right I didn't pay attention to this function. Thanks for this great lib !

Another Question: What about a computed field ? its value will be the result of the function the field receive. We can see this in ndb of google app engine:
https://cloud.google.com/appengine/docs/python/ndb/properties#computed

**Comment by jaimegildesagredo** [comment]
Thank you @ElielHaouzi :)

There is not a "computed field" yet. A similar behavior can be achieved using the `default` argument [[0]], that can be a function that will be called to get the default value for a field. The default value for a field is set the first time this field is accessed.

```python
from booby import Model, fields

class SomeEntity(Model):
  name = fields.String()
  name_lower = fields.Field(default=lambda self: self.name.lower())

x = SomeEntity(name='Nick')
x.name_lower  # 'nick'
```

This is a little tricky, but could be a workaround until a "computed" field is added. I think that this will not take long.

[0]: http://booby.readthedocs.org/en/v0.7.0/fields.html#fields.Field

**Pull request closed without merging**
